### ISSUE TITLE
Cannot insert custom emojis with company-emojify

### ISSUE THREAD

**Issue by luiznux** [jcs-elpa/company-emojify#1]
Hi!
I have the following config for emojify and company-emojify:
```elisp
(require 'my-custom-emojis)
  (use-package emojify
    :hook (after-init . global-emojify-mode)
    :bind ("C-c m" . 'emojify-insert-emoji)
    :init
    (setq emojify-company-tooltips-p   t
          emojify-display-style        'image
          emojify-composed-text-p      nil
          emojify-user-emojis          my-custom-emojis)

    (with-no-warnings
      (when (featurep 'emojify)
        (emojify-set-emoji-data)))

    ;; Others emojis fonts
    (cl-loop for font in '("Noto Color Emoji" "Apple Color Emoji")
             when (font-installed-p font)
             return (if (>= emacs-major-version 28)
                        (set-fontset-font t 'emoji (font-spec :family font) nil 'prepend)
                      (set-fontset-font t 'symbol (font-spec :family font) nil 'prepend)))
    :config
    (use-package company-emojify
      :init
      (setq company-emojify-emoji-styles '(github))
      (add-to-list 'company-backends 'company-emojify)))
```
The variabel *my-custom-emojis* is a list with all my custom emojis, when i use *emojify-insert-emoji* my custom emoji is inserted with success, but with company-emojify the following error is returned:

![image](https://user-images.githubusercontent.com/48339190/227582513-25941084-f292-4ca5-b9bf-2b734faae956.png)

![image](https://user-images.githubusercontent.com/48339190/227580153-83f7c392-d03b-4815-9237-9760faedfd37.png)

The config for the current emoji is:
![image](https://user-images.githubusercontent.com/48339190/227582259-2d962506-f335-4e08-96f0-908efa0bc62b.png)

Is possible to insert custom emojis with company-emojify ?

**Comment by jcs090218** [comment]
Yes, this package insert unicode by default. You will need to add it to the property list:

```diff
(setq emojify-user-emojis
      '((":trollface:" . (("name" . "Troll Face")
                          ("image" . "~/.emacs.d/emojis/trollface.png")
                          ("style" . "github")
+                          ("unicode" . "UNICODE-HERE")))
        (":neckbeard:" . (("name" . "Neckbeard")
                          ("image" . "~/.emacs.d/emojis/neckbeard.png")
                          ("style" . "github")
+                          ("unicode" . "UNICODE-HERE")))))
```

If you want to turn off the unicode insertion, do `(setq company-emojify-insert-unicode nil)`.

**Comment by luiznux** [comment]
Thank you very much! Now it's working perfectly :)
